### ISSUE TITLE
Error on running Photon-WebUI

### ISSUE THREAD

**Issue by memory125** [alanzhangzm/Photon-WebUI#2]
I followed your guide on running this sample.
* 1. Install dependencies via `npm install`.
* 2. Run the sample via `npm run dev`.

But it fails with the following error.
```
Error: Cannot find module '\Photon\Photon-WebUI\build\webpack.dev.conf.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at WEBPACK_OPTIONS \Photon-WebUI\node_modules\webpack-cli\bin\convert-argv.js:133:13)
    at requireConfig (\Photon-WebUI\node_modules\webpack-cli\bin\convert-argv.js:135:6)
    at \\Photon-WebUI\node_modules\webpack-cli\bin\convert-argv.js:142:17
    at Array.forEach (<anonymous>)
    at module.exports (\Photon-WebUI\node_modules\webpack-cli\bin\convert-argv.js:140:15)
    at Object.<anonymous> (\Photon-WebUI\node_modules\webpack-dev-server\bin\webpack-dev-server.js:92:55)
```
I checked the configuration, there is no `build` folder in this repo. And your configuration `.eslintignore ` file specified that  `/build/` is ignored.

**Comment by memory125** [comment]
So my question is how to fix this issue?

**Comment by memory125** [comment]
Any updates?

**Comment by alanzhangzm** [comment]
I migrated the project to use a template generated using Vue-CLI 3. The issue has been addressed.
